package net.interdoodle.hbe.domain

import collection.mutable.HashMap

/**
 * @author Mike Slinn */

class TextAnalysis {
  /** Contains all text generated by a Monkey; only grows in length, nothing is ever deleted */
  val text = ""

  /** Maps startPos to (length, startPos, endPos)
   * This makes it easy to update matches that grow between pages */
  var resultMap = new HashMap[Int, (Int, Int, Int)]


  def addTextMatch(length:Int, startPos:Int, endPos:Int) {
    resultMap += startPos -> (length, startPos, endPos)
  }
}